version: '2.4'

# environmental variables *for Docker Compose* will be loaded from a `.env` file
# in the same directory as this file

services:
  pypi:
    # image: stevearc/pypicloud:1.0.10-py3-alpine
    # build: ../../build/pypi
    image: minchinweb/pypi
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9920:8080
    volumes:
      - ${DOCKER_USERDIR}/volumes/pypi:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.pypi.rule=Host("pypi.${LOCAL_DOMAIN_NAME}")  # 2.0
      - traefik.http.routers.pypi.entrypoints=web
      # - traefik.http.services.pypi-service.loadbalancer.server.port=8080
      # - traefik.http.routers.pypi.service=pypi-service

networks:
  default:
    external:
      name: meta_external
